# mkdocs.yml

site_name: Clearstone SDK
site_description: "The open-source reliability toolkit for AI agents. Add production-grade governance, observability, and debugging to any agent workflow."
site_url: https://sancauid.github.io/clearstone-sdk/
repo_url: https://github.com/Sancauid/clearstone-sdk
repo_name: Sancauid/clearstone-sdk
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 Clearstone.dev

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Sancauid/clearstone-sdk
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/clearstonedev
    - icon: fontawesome/brands/discord
      link: https://discord.gg/VZAX4vk8dT
    - icon: fontawesome/solid/paper-plane
      link: mailto:pablo@clearstone.dev

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

nav:
  - 'Overview': 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'User Guide':
    - 'Core Concepts': 'guide/core-concepts.md'
    - 'Governance': 'guide/governance.md'
    - 'Observability': 'guide/observability.md'
    - 'Testing': 'guide/testing.md'
    - 'Time-Travel Debugging': 'guide/time-travel-debugging.md'
  - 'Pre-Built Policies': 'policies.md'
  - 'Join Waitlist': 'https://t.co/4geEAPFzXC'
  - 'API Reference':
    - 'Governance API': 'api/governance.md'
    - 'Observability API': 'api/observability.md'
    - 'Testing API': 'api/testing.md'
    - 'Debugging API': 'api/debugging.md'
    - 'Utilities API': 'api/utils.md'
  - 'About':
    - 'Contributing': 'about/contributing.md'
    - 'Telemetry': 'about/telemetry.md'
    - 'License': 'about/license.md'
